title: Primative – Web development
DefaultContentLanguage: en
enableRobotsTXT: true
disableHugoGeneratorInject: true
enableMissingTranslationPlaceholders: true
pygmentStyle: dracula
baseUrl: https://primative.net
sectionPagesMenu: main
googleAnalytics: UA-28964878-1

permalinks:
  blog: /:section/:slug/
  projects: /:section/:slug/

blackfriday:
  angledQuotes: true
  extensions:
    - hardLineBreak

languages:
  en:
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: About
          url: /about
          identifier: about
          weight: 2
        - name: Projects
          url: /projects
          identifier: projects
          weight: 3
        - name: Blog
          url: /blog
          identifier: blog
          weight: 4
  fr:
    menu:
      main:
        - name: Accueil
          url: /
          weight: 1
        - name: À propos
          url: /about
          identifier: about
          weight: 2
        - name: Projets
          url: /projects
          identifier: projects
          weight: 3
        - name: Blog
          url: /blog
          identifier: blog
          weight: 4
