DefaultContentLanguage = "en"
baseURL = "https://www.primative.net"
disableHugoGeneratorInject = true
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
googleAnalytics = "UA-28964878-1"
pygmentStyle = "dracula"
removePathAccents = true
sectionPagesMenu = "main"
title = "Primative – Web development"
[blackfriday]
angledQuotes = true
extensions = ["hardLineBreak"]
[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2
[[languages.en.menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 3
[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 4
[[languages.fr.menu.main]]
name = "Accueil"
url = "/fr/"
weight = 1
[[languages.fr.menu.main]]
identifier = "about"
name = "À propos"
url = "/about/"
weight = 2
[[languages.fr.menu.main]]
identifier = "projects"
name = "Projets"
url = "/projects/"
weight = 3
[[languages.fr.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 4
[params.staticman]
branch = "master"
endpoint = "https://api.staticman.net/v2/entry"
repository = "primative.net"
username = "fbnlsr"
[permalinks]
blog = "/:section/:slug/"
projects = "/:section/:slug/"
