[context.production.environment]
  HUGO_VERSION = "0.34"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.34"

[[headers]]
  for = "/*"
    [headers.values]
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Strict-Transport-Security = "max-age=10886400; includeSubDomains; preload"
