---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
  content/projects:
    default_front_matter_template: projects
  content/blog:
    default_front_matter_template: blog
upload_dir: static/img/posts
public_path: "/img/posts"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.37.1
